export const __STORENOTIFY_CARTITEMS = "__STORENOTIFY_CARTITEMS";
export const __STORENOTIFY_USERINFO = "__STORENOTIFY_USERINFO";
export const __STORENOTIFY_SHIPPING_ADDRESS = "__STORENOTIFY_SHIPPING_ADDRESS";
export const __STORENOTIFY_PAYMENT_METHOD = "__STORENOTIFY_PAYMENT_METHOD";
